node_env: "development"
url_db: "postgres://postgres:123456@localhost:5432/device_service_db?sslmode=disable"
name_service: "DeviceService"
port_grpc: 50060
host_grpc: "localhost"
interval_check: "20s"
timeout_check: "15s"

url_mqtt: "tcp://127.0.0.1:1883"
username_mqtt: "admin"
password_mqtt: "123456"
client_id_mqtt: "device_service"
tls_mqtt: false